@startuml
'https://plantuml.com/object-diagram

object originator

originator : Memento getMemento()
originator : void setMemento()

object memento
object "care taker" as caretaker

originator o-- memento
@enduml
